build_docker:
  stage: build
  image: $CI_REGISTRY/ezone-public/docker:dind
  services:
     - name: $CI_REGISTRY/ezone-public/docker:dind
       alias: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/x_hub/blog:latest .
    - docker push $CI_REGISTRY/x_hub/blog:latest